# Generated by Django 5.0.6 on 2026-07-18 19:28

import apps.baby.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baby', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='babyprofile',
            name='room_id',
            field=models.CharField(default=apps.baby.models.generate_room_id, max_length=16, unique=True),
        ),
    ]
